// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Copyright 2008 Google Inc. All Rights Reserved.

syntax = "proto2";

package apphosting;

import "images_service.proto";

option java_package = "com.google.appengine.api.images.proto";
option java_outer_classname = "ImagesServiceRPC";
option java_multiple_files = true;

service ImagesService {
  // Perform transformations on the given image and return the result.
  rpc Transform(java.apphosting.ImagesTransformRequest)
      returns (java.apphosting.ImagesTransformResponse) {}

  // Composite images onto a canvas and return the result.
  rpc Composite(java.apphosting.ImagesCompositeRequest)
      returns (java.apphosting.ImagesCompositeResponse) {}

  // Calculate the histogram of an image and return it.
  rpc Histogram(java.apphosting.ImagesHistogramRequest)
      returns (java.apphosting.ImagesHistogramResponse) {}

  // Obtains a URL that can serve the image dynamically at different sizes.
  // The URL format will look like the following:
  //
  // http://lh3.ggpht.com/SomeEncryptedString
  //
  // to serve this image at different sizes just append the size option:
  //
  // http://lh3.ggpht.com/SomeEncryptedString=s128 (serves a 128 sized image)
  //
  // The allowed thumbnail sizes are any integer in the range [0, 1600].
  rpc GetUrlBase(java.apphosting.ImagesGetUrlBaseRequest)
      returns (java.apphosting.ImagesGetUrlBaseResponse) {}

  // Delete a URL that was created with GetUrlBase
  rpc DeleteUrlBase(java.apphosting.ImagesDeleteUrlBaseRequest)
      returns (java.apphosting.ImagesDeleteUrlBaseResponse) {}
}
